### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#1016]
I see some problems in the new log formatting that makes debugging in AWS extremely painful:
- Everything is a one liner,  in order to understand what's going on, we need to unfold every single line. I know we can filter, but sometimes i want to see what's going on.
- The one line summary contains in my opinion irrelevant and duplicated information: for example, we have timestamp twice, pid, hostname, correlationId.... and finally message (sometimes called msg. Maybe it should be uniform). There should be a way to either configure what we want in these logs, or at least put relevant information first (message, block, transaction,....). The way its currently ordered, important information doesnt fit in the screen

My suggestion is to either:
1. change order of how  JSON log fields are displayed. Leave time, pid, hostname and correlationId at the end
2. Enable configuration of which fields are displayed.

I think 1. is good enough.

**Comment by israelboudoux** [comment]
The `pid` and `hostname` fields were not supposed to be displayed, there is a PR handling this. There were some parts in the code that were using `message` that are now addressed in the same PR. The `time` field isn't duplicated, it is the time the event occurred in the server x the time the log was received by CloudWatch, and as CW is a native tool in AWS it receives the logs instantly, but if these logs get sent to another Logging tool it will have to rely on this field for event timing.

**Comment by signorecello** [comment]
Hey @druiz0992 I believe we can achieve 2 pretty easily without changing code, as we can use log insights on AWS and separate fields, filter them, reorder according to a specific filter, etc. For example, you could use it to only show messages, filter by a specific `correlationId` (so it only shows logs regarding one specific transaction among potentially thousands), on a specific time window, etc.

From my knowledge of AWS, log insights is actually the "correct" way of using the logs. Log groups are OK for quick debugging but JSON format shows stringified and it's harder to read.

**Comment by pawelgrzybek** [comment]
@signorecello Log insights and its powerful querying system is super powerful, but we need to keep in mind this is a paid service. We can refactor our logger to log stringified data for this one to appear in the logs in one line and avoid spreading across muti-line comments.
