### ISSUE TITLE
Automate @polygon-nightfall/common-files release to npm

### ISSUE THREAD

**Issue by pawelgrzybek** [EYBlockchain/nightfall_3#1055]
Currently, every change to `common-files` requires a manual deployment to `npm`. This thing should be automated as part of the pipeline. Helpful commands.

```
npm diff
```

```
npm publish
```

If you are still not part of the `@polygon-nightfall` npm org, please let me know, I am happy to add you!

**Comment by pawelgrzybek** [comment]
@israelboudoux I may need your help on this oen as some point, probbaly early next week my friend ❣️

**Comment by israelboudoux** [comment]
> @israelboudoux I may need your help on this oen as some point, probbaly early next week my friend heavy_heart_exclamation

I'm at your disposal! :D
