### ISSUE TITLE
GHA check gas for 32 tx per block sometimes failing

### ISSUE THREAD

**Issue by daveroga** [EYBlockchain/nightfall_3#1128]
Test check gas for 32 transaction per block sometimes failing with `Error: socket hang up` during the test

![image.png](https://images.zenhubusercontent.com/615b1480539a0a0f1387eadf/059be97b-5e4e-487a-b05b-557764da12b1)

**Comment by druiz0992** [comment]
![Screenshot from 2022-10-24 10-09-04](https://user-images.githubusercontent.com/46495002/197490789-a08aaa82-438d-4c06-a2e2-0544fbbd0a1c.png)
