### ISSUE TITLE
Implement an MVP - One proposer route

### ISSUE THREAD

**Issue by signorecello** [EYBlockchain/nightfall_3#1163]
As a proposer, I want to be sure the work is done without breaking changes. For that, I need to provide a simple MVP of the new changes.

- [x] Instead of sending the result of `encodeABI()` for the `registerProposer` call to the blockchain, sign it directly on the optimist

- [x] Remove the signing from the `nf3` file

To cover min functionality as described in #1111. Investigate how the tx queue/propose block processes work/can be achieved.

**Comment by imagobea** [comment]
Findings so far:

- I cannot pass env vars upon `start-nightfall`
- Every time I `start-nightfall` the db is clean - no traces of `optimist_data`
- Even if I pass the `-d` flag upon `start-nightfall`, I need to stop and start nightfall to "see" the latest changes
- We're opening a blockchain websocket from "common-files/utils/contract.mjs". This is happening in the client and optimist containers. This websocket uses `Web3` object from "common-files/utils/web3.mjs".
- Trying to re-use this `Web3` from common-files to sign transactions
- In progress
