### ISSUE TITLE
Automated integration testing should include tests against a Geth private chain

### ISSUE THREAD

**Issue by Westlad** [EYBlockchain/nightfall_3#117]
By default, we test against a Ganache instance, equivalent to starting Nightfall_3 with `./start-nightfall -g`.  However, we should also test against the Geth backend, equivalent to `./start-nightfall -e` because some tests will pass with Ganache but fail with Geth unless specifically coded for.  In particular the 'time-jumps' that Ganache can do are not available with Geth and the error messages differ.

**Comment by IlyasRidhuan** [comment]
Should this also start to use non-stub circuits?
