### ISSUE TITLE
Make new Geth tests in GitHub Actions

### ISSUE THREAD

**Issue by Westlad** [EYBlockchain/nightfall_3#133]
The previous Geth tests have been removed because they no longer work.  However it would be great to reinstate them based around the new approach of running the Geth blockchain as a separate docker project.  One issue with doing this is that the new Geth tests make use of the Mac-specific reference to the docker host (`host.docker.internal`), so that Nightfall_3 can access the Geth blockchain via the Mac localhost ports.  This may be hard to work around.

**Comment by Westlad** [comment]
PR #130 has instructions for running the new Geth tests.

**Comment by druiz0992** [comment]
We will run geth tests on Jenkins
