### ISSUE TITLE
make SDK browser compatible

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#190]
Currently, SDK uses .mjs files which are incompatible with browser. Refactor SDK to be browser compatible

**Comment by IlyasRidhuan** [comment]
I would assume the incompatibility issues arise at the `import` stage as that is where es6 differs the most from cjs.

Aren't `.mjs` files supported in the browser via `<script type="module" src ="[filename].mjs" >` ?

**Comment by druiz0992** [comment]
Maybe, I will try it as well. For now, I have used babel to create this version
