### ISSUE TITLE
Generate proofs for NF3 circuits with zokrates js provided wasm

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#225]
Exploring the feasibility of generating NF3 proofs in a browser using zokrates js wasm for proof generation. Ensuring that the memory provided by a browser is sufficient

**Comment by dwebchapey** [comment]
deposit.zok implemented in zokrates js [here](https://github.com/dwebchapey/zokrates-js-circuits)

**Comment by dwebchapey** [comment]
`double_transfer.zok` faces JS heap issue for compile .Other 3 circuits compiled in wasm. Timing for `single_transfer.zok` (in secs)

- Compile 20.998
- keypair 678.781
- compute witness 4.876
- generate proof 78.775


Zokrates currently supports only `(bn128, bellman, g16)` .  Wasm integration easier for bellman and ark than libsnark.

**Comment by dwebchapey** [comment]
In Zokrates-js circuits, Variable in for loop cannot have type field
solve by refactoring field type to u32 -  ` for u32 i in 0..32 do `

**Comment by dwebchapey** [comment]
`generate proof` operation in `zokrates js` is approx 5 times slower compared to `zokrates cli ` . proof generation for double transfer circuit took 144.86 secs in zok js compared 28.92 secs when using zok cli.
`witness computation` produce similar timings (8 secs for double transfer circuit).

**Comment by ChaitanyaKonda** [comment]
generate proof for double transfer should now work in browser using zokrates-js
