### ISSUE TITLE
explore alchemy node provider  

### ISSUE THREAD

**Issue by LijuJoseJJ** [EYBlockchain/nightfall_3#271]

**Comment by LijuJoseJJ** [comment]
Findings on Alchemy:-
1. it has monthly transaction compute unit unlike infura which has dailt transaction count ( To understand call and their compute units https://docs.alchemy.com/alchemy/documentation/compute-units)
2. Alchemy suggest to use their own wrap web3 (https://github.com/alchemyplatform/alchemy-web3)
     Note: not properly tested but seem web3.eth.subscribe of web3.js is not working.
     And all the documentation Alchemy use their own package called alchemy-web3. I am afraid Alchemy does not support web3.js ( I have not done proper test for it

**Comment by ChaitanyaKonda** [comment]
Moving to Geth
