### ISSUE TITLE
non ERC20 functionality in SDK

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#277]
There is some functionality missing in the SDK to manage non ERC20 tokens:
- Retrieve the ERC721/ERC155 tokenId present in the Ethereum wallet?
- Balance per tokenID.
- Get contract type from address (i,e, is it a ERC20, ERC1155 or ERC721 token)?

Some further study is necessary to identify the needs of this task. For now, it is just a placeholder:

**Comment by daveroga** [comment]
Already merged in wallet-refactor PR
