### ISSUE TITLE
Create a Ropsten Geth Server 

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#281]
- Create a server that runs Geth node
- The server should have enough storage for a Geth ropsten full node 
- The server should be run as a daemon (service)
- The server's JSON-RPC 8545 port will be closed for outside world 
- The server's peer to peer port 30303 will be opened to the outside world    
- The server should sit within the same VPC as the other nightfall servers

**Comment by druiz0992** [comment]
IP is 18.203.135.224

**Comment by druiz0992** [comment]
Services deployed here:
```
 clientApiUrl: 'https://client1.testnet.nightfall3.com', => port 8080
 optimistApiUrl: 'https://optimist1.testnet.nightfall3.com',  => port 8081
 optimistWsUrl: 'wss://optimist1-ws.testnet.nightfall3.com', => port 8082
 web3Url: 'wss://ropsten1.testnet.nightfall3.com' => port 8545
 web3WsUrl: 'wss://ropsten1-ws.testnet.nightfall3.com' => port 8546
```
