### ISSUE TITLE
Create functionality for MPC Ceremony using Zokrates

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#282]
This issue should work on the recommendation from the issue #191.
Currently ZoKrates team is looking into writing this functionality.
This issue should be updated with progress every week, so that we can decisions accordingly.

**Comment by dwebchapey** [comment]
Zokrates MPC functionality merged to main develop branch .

- The toolbox explanation can be found at [https://github.com/Zokrates/ZoKrates/blob/develop/zokrates_book/src/toolbox/trusted_setup.md](url)
-  A zokrates cli script for testing available at [https://github.com/Zokrates/ZoKrates/blob/develop/zokrates_cli/examples/book/mpc_tutorial/test.sh](url)

**Note**

- Currently works only for zokrates cli
- To run for circuits with larger constraints , clone the repo (https://github.com/kobigurk/phase2-bn254) and  run this script https://github.com/kobigurk/phase2-bn254/blob/master/powersoftau/test.sh#L11, change the SIZE var to the degree you want eg. 21, also you can minimize this script a bit to have a single contribution which is enough for testing
