### ISSUE TITLE
State where current proposer is not able to propose new blocks and fails with error 'The block is out of order'

### ISSUE THREAD

**Issue by daveroga** [EYBlockchain/nightfall_3#327]
Doing tests in testnet we have arrived to an state where the current proposer is not able to propose new blocks because is receiving error `The block is out of order` from the State.sol contract when trying to call `proposeBlock`.

It seems is something related with the change of current proposer that some blocks are already generated but not submitted on chain and then other proposer get the chance of current proposer and the blocks generated are being accumulated giving that error when trying to propose blocks.

Do some tests in local to reproduce this state and figure out then how to solve it.

**Comment by IlyasRidhuan** [comment]
Just to summarise the minimal necessary state flow:

1. Proposer_A is registered on-chain, is the `currentProposer` and running on `optimist-1`.
2. Proposer_B is registered on-chain and also running on `optimist-1`.
3. Propose_A proposes 2 blocks , however only 1 block is mined on-chain.
4. Rotate `currentProposer` to Proposer_B.
5. Feed more transactions to Proposer_B to get it to make a block. It should incorrectly create `blockNumberL2= 3` when it should be `blockNumberL2=2`.

Point (2) can be achieved in testing by using the websocket in the test to drop the second block.

The problem manifests as a result of the sharing of `optimist-1` by 2 proposers that are consecutive `currentProposers`. This results in them sharing local `Block` states, and can probably be solved with a `Block.rollback()` in `NewCurrentProposerHandler`.

**Comment by daveroga** [comment]
Defined test in branch `daveroga/proposers-bug-test` with 2 proposers to reproduce the state for `The block is out of order` when changing current proposer and some blocks pending from first current proposer.

- `npm run test-proposers` to run the test.

**Comment by daveroga** [comment]
We have done some tests with @IlyasRidhuan  and with his PR this problem is already solved.
