### ISSUE TITLE
During double transfer, the same commitment is being picked twice

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#336]
During `double transfer`, the same commitment is being picked twice by `findUseableCommitments`. 
To replicate this error, create a block with two ERC20 deposits of value 1000 each and then create a block with two ERC20 transfers of value 5 each. You will notice `findUseableCommitments` will pick the same commitment to spend twice.

**Comment by IlyasRidhuan** [comment]
That is weird - the likely problem is when all commit values in the DB are greater than the target value. Then  `commitsLessThanTargetValue` will be empty and it's `length === 0`, then unfortunately `sortedCommits[commitsLessThanTargetValue.length] === sortedCommits [0]` which causes the duplication.

![image](https://user-images.githubusercontent.com/9293647/144009345-4ee1515c-388d-42c0-a27d-dcf58f248abc.png)

There is also a gap in `duplicateNullifier` check in `optimist` where it only compares the transaction's nullifiers with nullifiers it has seen before - not factoring possible duplicates within the transaction itself. This is also true for the `block` check for `duplicateNullifier`
