### ISSUE TITLE
Remove requests to optimist for client-specific sdk calls.

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#338]
`requestInstantWithdrawal` and  `isValidWithdrawl` are two `client` calls currently in the sdk that make api calls to `optimist` to receive block information that are input parameters to these calls.

We have since removed this dependency on `optimist` for input and `client` now has the relevant information. We should also change this behaviour in sdk.

**Comment by daveroga** [comment]
Already merged in wallet-refactor PR
