### ISSUE TITLE
Block challenges for the first block

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#340]
This applies to Invalid Root and Invalid Leaf Count challenges.

When creating these challenge against block n, we need to retrieve the transactions from block n-1 or the frontier from block n-2.

If n == 0 (the first block), the challenge throws an error as the transactions for `blockNumberL2 === -1` is understandably not found.

The challenge should be modified such that we can still challenge this block.

**Comment by ChaitanyaKonda** [comment]
To note `Incorrect root` challenge expects two prior blocks

**Comment by dwebchapey** [comment]
Bootstrapping Nightfall by making sure first few blocks are good blocks which means that challenges to first block will not be made and therefore doesn’t require to be handled.

**Comment by ChaitanyaKonda** [comment]
A user script that creates enough transactions for two blocks is required. 
This script should 
- create atleast 2 transfers amongst deposit (helps in creating duplicate nullifier or historic root error bad block types by adversary in adversary testing. But this doesn't compromise L2)
- should work with browser based deployment or client based deployment
