### ISSUE TITLE
integrate zokrates-js with wallet UI app

### ISSUE THREAD

**Issue by LijuJoseJJ** [EYBlockchain/nightfall_3#345]
- integrate zokrates.js with wallet UI app
- also, bundle pk and compile out for all operation (deposit, withdraw, single-transfer and double-transfer) to wallet UI app
- make generate proof work in browser(wallet ui app) with static/hardcoded input for now

**Comment by LijuJoseJJ** [comment]
Decided not two create PR for now.
work in done and pushed to liju.jose/wallet-integrated-zokratesJS-2

**Comment by IlyasRidhuan** [comment]
Closing as we now have `wallet/nf-browser-v2` as the latest working branch
