### ISSUE TITLE
Replace compilation and setup in deposit with pre-computed values

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#353]
`wallet/nf-browser` contains the current `nightfall-browser` work.

The `deposit` function currently has to compile the circuits and do the key setup. This is not desirable and no longer needed as we now have a way to load pre-compiled circuits and the pre-generated keys. As a starting point, we should remove these unnecessary calls in `deposit` and replace them with the values in the browser.

This will also make it easier to update the `transfer` and `withdraw` calls.

This will likely need to be loaded into the browser on startup and stored - either in `localStorage`  or `indexedDB`.

**Comment by LijuJoseJJ** [comment]
hi @IlyasRidhuan 
listing down issue I am facing on `wallet/nf-browser` branch
1. `./proposer` script is not working 
2. wallet `npm start` is failing 
<img width="1662" alt="Screenshot 2021-12-07 at 2 02 39 PM" src="https://user-images.githubusercontent.com/36976825/144994375-bd441559-a5c4-4081-ac50-56d76ca0e6dd.png">
<img width="1320" alt="Screenshot 2021-12-07 at 1 53 59 PM" src="https://user-images.githubusercontent.com/36976825/144994422-10fcf576-c3d8-4876-a6c2-27895e7252b6.png">

proposer script error is not anymore in master

**Comment by LijuJoseJJ** [comment]
hi @IlyasRidhuan 
I pushed code to `liju.jose/wallet-integrated-zokratesJS-3` branch, i have completed deposit work in it (generate proof happing in browser using binaries of pk and compile file), also branch is rebased over latest master( time I writing this comment). 
Currently master branch has bug deposit of ERC20 approve which make deposit tx to fail
<img width="1680" alt="Screenshot 2021-12-10 at 2 42 48 PM" src="https://user-images.githubusercontent.com/36976825/145548520-94723408-fcf2-4b2b-b5ee-77ccf0bbfee7.png">

this bug exit in my deposit work also in branch  `liju.jose/wallet-integrated-zokratesJS-3`

**Comment by LijuJoseJJ** [comment]
Hi @IlyasRidhuan 
above mention bug is fixed in branch `liju.jose/wallet-integrated-zokratesJS-3` also deposit work is finished in it.
branch `liju.jose/wallet-integrated-zokratesJS-3` have master rebase till merge of david's wallet refactor PR ( on branch `david/wallet-refactor`)

**Comment by LijuJoseJJ** [comment]
[zokrates-make-binary.zip](https://github.com/EYBlockchain/nightfall_3/files/7700711/zokrates-make-binary.zip)

In Attachment - this is code to write binary file(compile out file and pk file) for a circuit, so according to Hari he didn't had exact circuits copied from Miranda work on publcInput Hash removal. This zip file has code which take .zok circuit file and create two binary files and two json file (binary file - `program` [compile out file] and `pk` [pk after setup])

so once Miranda branch https://github.com/EYBlockchain/nightfall_3/pull/332 is merged, we can use attached zip code to generate required file for us

**Comment by LijuJoseJJ** [comment]
work and fixes pushed to branch`wallet/nf-browser-v2`
