### ISSUE TITLE
Negative Challenge Testing

### ISSUE THREAD

**Issue by MirandaWood** [EYBlockchain/nightfall_3#357]
I think we should add negative tests for the challenges, i.e. run all the challenges on a good block and ensure they fail. 

Not an urgent issue, but it would help us with bug hunting. In some places we are expecting only failures, e.g. a failed verify call, so  incorrect failures are not being caught.

**Comment by dwebchapey** [comment]
Good blocks challenges are accepted for certain challenges . These need to fixed first before continuing neg challenge testing.
The challenges that are passing successfully for good blocks are: 
1. Invalid transaction type challenge - A new issue #424 is created and fix is provided in PR #432 
2. Proof verification challenge - Good blocks accepted for double transfer , single transfer and withdraw

**Comment by druiz0992** [comment]
issue should cover:
- Perform and verify resilience to negative testing with adversary
- Robustly testing all types of negative blocks as well as good blocks against challengers
