### ISSUE TITLE
Liquidity provider approve withdraw

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#358]
Currently, liquidity provider does this in `cli/src/liquidity-prodiver.mjs`:
```
await approve(
    erc20Address,
    nf3.ethereumAddress,
    nf3.shieldContractAddress,
    'ERC20',
    '1000000000000',
    nf3.web3,
  );
```
where contract address, erc type and amount are constants. This information should be retrieved from the withdrawal transaction hash and not be a constant.

**Comment by daveroga** [comment]
Pushed a branch `daveroga/instant-withdraw-approve-sdk` that solves it in sdk.
