### ISSUE TITLE
wallet - token balances

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#364]
Review way token balances are updated in the wallet. Some the issues found are:
- When switching accounts, previous balances are displayed for a brief time
- When doing a ERC 20 deposit and a ERC721 transfer, it seems that ERC721 balances take longer to refresh
- It seems that updated take longer than they should.

**Comment by IlyasRidhuan** [comment]
Closing as new browser-wallet work is in progress
