### ISSUE TITLE
wallet - redesign withdraws

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#368]
Currently, instant withdraw can be selected in the wallet when doing a withdraw. Redesign this functionality so that the user can preview the current withdraws and either perform an instant withdraw or a finalize.

**Comment by druiz0992** [comment]
My idea is to move the operations like remove and add tokens to a side menu. In this side menu, add option to check withdraw statatus

**Comment by IlyasRidhuan** [comment]
Closing as new browser-wallet work is in progress
