### ISSUE TITLE
Remove subdirectory-level Dockerfiles

### ISSUE THREAD

**Issue by Westlad** [EYBlockchain/nightfall_3#374]
We now have two Dockerfiles for each component. These are the ones in the root directory, used to make docker images, and those in each component subdirectory, used by `docker-compose.yml`.  We should only have one because of the DRY principle, and also some code is broken because we're not updating both.

It seems best to keep the ones in the root because these don't have the problem that their context is limited a subdirectory. The latter makes it hard to incorporate code which is common across subdirectories.

**Comment by MirandaWood** [comment]
Just to note that the root level dockerfiles are designed for kubernetes deployment, so they minimise binds where possible. They copy over directories of code so we don't need to define bind mounts in docker-compose. See `docker-compose.images.example.yml` for what binds are needed/not needed

**Comment by Westlad** [comment]
That's fine, and actually how it should be done.  When a bind mount is done, the bind mount will trump the copied directory.  If you don't do a bind mount (e.g. for production) then it should use the copied versions.
