### ISSUE TITLE
Get wallet working with a new testnet deployment

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#392]
- Deploy NF into a server using the instructions from [here](https://github.com/EYBlockchain/nightfall_3/tree/master/test/ping-pong) 
- The wallet will talk to the client deployed from the above
- Proposer, Liquidity Provider, Challenger users will be started from the same server
- Geth ropsten full node deployed in one of our servers will be used for this deployment

Definition of done: All the wallet functionality working on ganache to work with this ropsten testnet deployment

**Comment by druiz0992** [comment]
This issue requires the following PRs to be merged:
#334, #386, #389, #398 and #401

**Comment by ChaitanyaKonda** [comment]
This needs to be done but for the new wallet.
