### ISSUE TITLE
Style browser wallet similar to Polygon's website

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#393]
### Intro

The polygon web wallet project is using Vue.js and bootstrap for style the UX/UI. But our objective is continue using reactjs with bootstrap and have a link on polygon web wallet site for polygon nightfall wallet.

### Goal of this task is:

- Based on the polygon web wallet project bootstrap, add boostrap styles for our project.

### Definitions after meetings

Create a new page based on polygon wallet styles and start to add our features in this new page.

**Comment by ChaitanyaKonda** [comment]
Hey @luizoamorim I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/polygon-nightfall-6148eee81b1164001874730b/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by luizoamorim** [comment]
Meeting with polygon team to discuss about our necessities and align it with them.
Mon 17 JAN - 11:30 am London time

**Comment by luizoamorim** [comment]
### Definitions after meetings
Create a new page based on polygon wallet styles and start to add our features in this new page.

**Comment by luizoamorim** [comment]
# Issue Goal
The goal of this task was prepare a browser nightfall wallet for the demo on Wednesday JAN 26.
So for this demo will be necessary to show that we have the deposit, withdraw and send functions working with the new style. And finally show that the transactions are storaged

## What was done
- So first polygon gave us the access for their web wallet project. It is in Vue.js and basically using bootstrap for the styles. 
- We had some difficulties in some parts to pass their scss for our project, so we have some stuffs different in the code but equals or very similar at the screen view.
- Basically we've created new components and views in our wallet project and for each component exists a scss module file.
- The new style is integrated with the existent functions that were already working. And we need to create some new functions within the components.
- I thought the work planned was done. If you @ChaitanyaKonda and @IlyasRidhuan agree I'll close this issue.

## Next steps
- Create a project for the new nightfall wallet.
- Have a meeting with polygon team in the next week.
- Plan the next features to be created or refactored.

## Work done

### This is the main page:
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/8b45e484-55cb-4d10-9215-aa1c3c015a3e)

### This is the assets page:
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/804ae9dd-96fe-4e59-8b98-0b8095d1d82d)

### When click in the send button we have a modal:
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/41eb6691-94a3-4cd0-bcb9-4865407a19e5)

### When we click in deposit or withdraw goes to this page:
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/bb1c7586-c2cb-4c5e-a920-2138588ff149)

### When the user confirm the action start the modal flow:
![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/36fb080b-22a7-4818-8000-c30d0b053bb8)

![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/be70d296-2fe9-4326-9fc7-ce2aa972850d)
