### ISSUE TITLE
Make wallet error messages more descriptive

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#397]
Expanding #342 

Adding error messages to the wallet is a good feature. Now, we can make the errors more descriptive so that the user knows what to do next.
- For example, after transfer without sufficient balance, it says 'transfer failed'. This could be 'Transfer failed: Insufficient Balance'
- For example, after deposit without resetting the metamask nonce, it says 'Deposit failed'. This could be 'Deposit failed: Incorrect Nonce`

**Comment by IlyasRidhuan** [comment]
Closing as new browser-wallet work is in progress
