### ISSUE TITLE
fix e2e test for balance check after deposit( env: ganache)

### ISSUE THREAD

**Issue by LijuJoseJJ** [EYBlockchain/nightfall_3#406]
Currently all PR to master sometime fail its github action check for e2e test 
<img width="1236" alt="Screenshot 2022-01-14 at 5 27 44 PM" src="https://user-images.githubusercontent.com/36976825/149512117-a8729d5c-0282-433f-a787-fa553df2fc65.png">

**Comment by druiz0992** [comment]
Issue may be fixed in #386

**Comment by ChaitanyaKonda** [comment]
Closing. Fixed
