### ISSUE TITLE
(nightfall-browser) remove old deposit, single-transfer, etc proof generation page 

### ISSUE THREAD

**Issue by LijuJoseJJ** [EYBlockchain/nightfall_3#414]

**Comment by IlyasRidhuan** [comment]
This is a good issue but we should leave these pages for now. Leave this issue up but tackle it later

I'm updating the static inputs in these files so they will accurately test against the circuits.

These are useful for dev as it helps to isolate the source of bugs without having to go through the entire deposit/transfer/withdraw work flow

**Comment by LijuJoseJJ** [comment]
already done
