### ISSUE TITLE
User should be able to retrieve balances based on token types or status

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#439]
Interpreting balances based on token types or status should be done in the browser/server apps considering the following
- It is a use case specific feature and as such should not be implemented in NC
- Front end needs more information based on token type such as decimals of the ERC20 that could reuse the code 

1. [ ] User should be able retrieve L1 ERC20 balance, L1 ERC721 balance and L1 ERC1155 balance
2. [ ] #436
3. [ ] #437
4. [ ] #438

Definitions:

- `L1 ERC20 balance`: as suggested by name
- `pending L2 ERC20 balance`: ERC20 balance from L2 blocks that are yet to be mined
- `L2 ERC20 balance`: ERC20 balance from L2 blocks that were mined
- `finalised L2 ERC20 balance`: ERC20 balance from L2 blocks that were mined and past the challenge period

Considerations
- A combination of address, ABI and ERC165 could be used to identify the type (ERC20/ERC721/ERC1155) of contract
- Do not use a permutation of `0` for `value` and `tokenId` to interpret token types because it ignored the edge cases when these could be `0`. EIPs for ERC20 and ERC721 define that `value` could be `0` and `tokenId` could be `0` respectively
- A combination of `isOnChain`, `isNullified` and `isNullifiedOnChain` from NC's commitments collection could be used to calculate the balance of tokens in various states (pending L2 and not confirmed L2)
- NC should only contain a generic function that retrieves all commitments based on `pkd`
- Any filtering logic should sit outside NC

**Comment by IlyasRidhuan** [comment]
Closed, this is already available in the wallet
