### ISSUE TITLE
Create ERC20 tests for Nightfall browser

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#447]
DoD: 
- Deposit and successful L1 and L2 balance update
- Direct Proposer and sent to blockchain transfer and successful L2 balance update for sender and receiver
- Direct Proposer and sent to blockchain withdraw and successful L2 balance update
- Instant withdraw and successful L1 and L2 balance update

**Comment by ChaitanyaKonda** [comment]
This might require the functionality is #437

**Comment by LijuJoseJJ** [comment]
@ChaitanyaKonda @IlyasRidhuan 
For now nightfall-browser does not have feature such as instant withdraw and direct proposer transfer.
PR #548 implements e2e test suits which check deposit, transfer(both single and double) and withdraw and do assertion and L2 balances
