### ISSUE TITLE
Clean up and Refactor PNF Browser

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#448]
In the previous sprint, we added some technical debt to the browser. We should clear this debt so that we have a clean platform to build new views and functionality.

### Clean Up
- [x] Investigate if we can use the same `class` styling approach as polygon but with `react`
- [x] Remove unused views from wallet subdirectory

### Refactor
- [x] Refactor `/initialPage`
- [x] Refactor `/wallet`
- [x] Refactor `/navbar`
- [x] Refactor `/sidebar`
- [ ] Refactor `/bridge`
- [ ] Refactor `/transactionPage`

**Comment by luizoamorim** [comment]
### About the task:  Investigate if we can use the same class styling approach as polygon but with react

Yes is possible do that. But was defined that we'll have two different projects. So we can do the styles in a best way for React JSX or TSX.

**Comment by ChaitanyaKonda** [comment]
-  Refactor /bridge
-  Refactor /transactionPage
Are no more a refactoring task. 
These need to be redesigned

**Comment by ChaitanyaKonda** [comment]
The ticked off changes are merged into `wallet/nf-browser-v2`.
