### ISSUE TITLE
Sketch out unique user interactions/flows for PNF Browser

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#449]
Some of our operations in PNF Browser involve user process flows that are unique to us.

This issue is concerned with building a skeleton for some of these flows. This will make it easier to convey to the Polygon Web Wallet designers what it is we need.

### List of Flows (more to be added as we think of them)
- [x] Indicating possible transfer/withdraw values based on currently available commitments
- [x] Instant Withdrawal / Finalise Withdrawal indicators
- [ ] Displaying transactions that have reverted because of Rollbacks from valid challenges
- [ ] Derive multiple addresses (pkds) from the same mnemonic
- [ ] ~Importing mnemonic (and multiple mnemonics) for PNF instead of generating a new one.~

**Comment by ChaitanyaKonda** [comment]
Closing this issue because the other tasks are pending web component integration
