### ISSUE TITLE
Plan and create deployment infrastructure 

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#473]
Design AWS network to support dev, staging and production environments.

- Deployment 1.0 (minimum required to work):
    - [x] Basic cloud infrastructure: VPC, subnets, GW, NAT, ACL....
    - [x] ECS with Fargate for container deployment in private subnets
    - [x] Public ALB to communicate with tasks
    - [x] EFS file system for deployer and optimist tasks
    - [x] Geth Ropsten
    - [x]  domain for each service deployed
    - [x] door to access environment
    - [x] internal ALB to access optimist

- 2.0
   - [x] MongodB
   - [x] SSH into containers
   - [x] VPN
   - [ ] Alams
   - [x] Duplicate Staging for Prod
   - [x] Pub-sub infrastructure
   - [x] Add second staging environment
   - [x] Deploy goerli node

**Comment by druiz0992** [comment]
![Nightfall](https://user-images.githubusercontent.com/46495002/152951366-d6072235-32e2-4d9e-80bb-6106e92ceff0.jpg)
