### ISSUE TITLE
Set up infrastructure to sent PNF3 events back to the browser.

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#481]
In place of opening a websocket directly between the `optimist` deployment in Ohio and the browser, we require a more robust way to communicate `blockProposed` and `Rollback` events back to the browser.

The medium term approach, until we have fully-fledged staging and production setups is captured by the image below.

![WS drawio](https://user-images.githubusercontent.com/9293647/153141262-23374600-0e6e-4bbd-b586-9ad568bc2783.png)

**Comment by ChaitanyaKonda** [comment]
Rollback handler to be implemented in a issue once adversary is merged to test it with
