### ISSUE TITLE
Create a web component for nightfall bridge element

### ISSUE THREAD

**Issue by luizoamorim** [EYBlockchain/nightfall_3#483]
![webComponentBridge.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/8c1eee0a-8db6-48d2-b7ea-dc284985fe3c)

Transform just the part in red in a new web component that we'll be used within polygon vue.js code.

If you want understand better about web components: https://developer.mozilla.org/en-US/docs/Web/Web_Components

**Comment by luizoamorim** [comment]
## What was done?
- I separated the code from the red part from the rest of the bridge page.
- Created a react Function Component for this code.
- Generate a web component for this react function component.
- Used this web component within the bridge page.

## How to create a new web component in React?
- I used the lib react-to-webcomponent. (https://www.npmjs.com/package/react-to-webcomponent)

### Implementing
- Is necessary call the library within the page that we want show our component.
- In this case we want to show the BridgeComponent (part in red in the picture) within the bridge page.
- For that we need to define this new web component at the moment that the page is mounted in DOM.
- So we define the web component using the hook useEffect within the page bridge.
```
const location = useLocation();

  useEffect(() => {
    defineComponents();
  }, [])

  function defineComponents() {
    customElements.define(
      'bridge-component',
      reactToWebcomponent(
        BridgeComponent, 
        React, 
        ReactDOM
      )
    )
    const bridgeComponent = document.createElement("bridge-component");    
    bridgeComponent.location = location;    
  }
```
- Then we need to insert the tag (<bridge-component />) for the new web component within the code:
```
return (
    // containerFluid
    <div>
      <Header />
      <div className={styles.bridgeComponent}>
        <div className={styles.bridgeComponent__left}>
          <SideBar />
        </div>
        <div className={styles.bridgeComponent__right}>
          <div className={styles.blueBack}>
            {/* <WarningBanner className="warning-banner" /> */}

            <div className={styles.pagePartition}>
              <div className={styles.infoWrapper}>
                . . .
              </div>
              <div><bridge-component /></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
```
## Result
The page is been showed correctly with the new web component.

**Comment by luizoamorim** [comment]
## Issue
Property 'tokenState' does not exist on type 'Location'.ts(2339)

@IlyasRidhuan let's see the best way to fix it.

Tks.

**Comment by IlyasRidhuan** [comment]
This should already be fixed in the latest of `wallet/nf-browser-v2` - we can look at porting it to the typescript file

**Comment by luizoamorim** [comment]
@IlyasRidhuan We're having this error when click in send transaction:

Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.

Do you hava any idea?

**Comment by luizoamorim** [comment]
The issue #512 is done. But now other problem comes:

Uncaught (in promise) 
Object { code: -32603, message: "[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"message\":\"the tx doesn't have the correct nonce. account has nonce of: 233 tx has nonce of: 236\",\"code\":-32000,\"data\":{

**Comment by IlyasRidhuan** [comment]
Ah this is a straightforward one and happens quite a lot when you use the local testing environment. You need to reset metamask (usually you need to do this whenever you reboot the web-server - `npm run sta

https://user-images.githubusercontent.com/9293647/154921708-1c29cd51-f635-4436-9def-07dfcac9fad6.mov

**Comment by luizoamorim** [comment]
Really. I'm forgot this. Let me test here.

**Comment by luizoamorim** [comment]
@IlyasRidhuan  Did you had this error in Commitment class?

Unhandled Rejection (Error): Property value was undefined. Did you pass the wrong object to the constructor?

**Comment by luizoamorim** [comment]
## Last problem in depoist.js file solved 

Function depoisit receive items like parameters. This items are a set of objects and one of these is value.
```
async function deposit(items, shieldContractAddress) {
  logger.info('Creating a deposit transaction');
  const { ercAddress, tokenId, value, pkd, nsk, fee } = generalise(items);
```
But we were passing 'state'  parameter in the place of 'value' parameter.
```
const { rawTransaction } = await deposit(
          {
            ercAddress,
            tokenId: 0,
            state: tokenAmountWei,
            pkd: state.zkpKeys.pkd,
            nsk: state.zkpKeys.nsk,
            fee: 1,
            tokenType: 'ERC20',
          },
          shieldContractAddress,
        );
```
I changed 'state' for 'value' and it works well:
```
const { rawTransaction } = await deposit(
          {
            ercAddress,
            tokenId: 0,
            value: tokenAmountWei,
            pkd: state.zkpKeys.pkd,
            nsk: state.zkpKeys.nsk,
            fee: 1,
            tokenType: 'ERC20',
          },
          shieldContractAddress,
        );
```

**Comment by luizoamorim** [comment]
commit a3bb862e6dd267379d0ffa3651d15a0feb37518e

**Comment by luizoamorim** [comment]
Web component working.
