### ISSUE TITLE
./proposer script fail due to commander and clear package missing in package.json

### ISSUE THREAD

**Issue by PeterCCLiu** [EYBlockchain/nightfall_3#489]
Hello,

After setup NF3 and get it running, when running `./proposer` script, missing module error pops out for `commander` and `clear`. 

Had to `npm install commander clear --save` to fix and `./proposer` ran without further errors.

Just for your information. 

Peter

**Comment by PeterCCLiu** [comment]
Also `figlet`, `inquirer` and `cli-table` for `./nf`

**Comment by druiz0992** [comment]
not valid with latest changes
