### ISSUE TITLE
Use Timber as basis for syncing in the browser

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#538]
The browser currently uses the `lastBlock` it has seen from the `Block_Collection` to perform a sync query with the DynamoDB.

However, the browser does not save every block (like `client` does) and so it ends up requesting blocks it has seen before but doesn't save.

While this is not an issue for most of its collections, it does cause an issue with `Timber`. This is because `timber` is saved with every block, therefore replaying these blocks causes timber to replay commitments into the tree with creates invalid trees.

Moving forward, the measure of `lastBlock` in the browser should be based on what is in the `Timber` database.

**Comment by ChaitanyaKonda** [comment]
Done because PR merged
