### ISSUE TITLE
Contract ownership will be trustless/decentralised

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#545]
Because a restricted beta launch is done prior to completion of audit and with less time on the testnet, we will require the upgradeability to fix any bugs in the contracts. For this reason, this will be initially launched with Polygon as contract owner.

After audit and confidence that major bugs have been handled, we will make this decentralised and trustless. 
For example, using a DAO etc.

**Comment by druiz0992** [comment]
This is done. Contract ownership is transferred to multisig
