### ISSUE TITLE
Assets Page + Send Modal

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#559]
The assets page displays the total value of the funds in nightfall. It also provides shortcuts to the send and receive functionality. The send modal enables selection of assets and value to send.

See sections 1 and 2 of the [HackMd](https://hackmd.io/@p4-pRlreS4a4NpxTZYUcMA/BJa1ntceq#7-Bridge-component) for visuals.

The completion of tasks will be based on corresponding PRs.

## UI Changes
- [x] Receive modal should show current pkd as well as QR code representation.
- [x] Send modal needs additional information page before enabling user inputs.
- [ ] ~Send modal needs to be extracted to its own component file as it is re-used across the browser.~
- [ ] ~Commitment selection in scenarios where transfer value is invalid.~ **Pending Polygon UX Team**

## Feature changes
- [x] Retrieve current pkd and generate QR code from this pkd
- [x] Spinner for send modal so that user understands proof generation is underway.
- [ ] Exception handling when invalid transfer value

**Comment by luizoamorim** [comment]
QRcode modal template 

![image.png](https://images.zenhubusercontent.com/61e15c65574e2d57bb040461/d96e9280-98a1-4bbb-9ff5-32d64c67666f)

width 480
height 507

**Comment by luizoamorim** [comment]
Branches created

   luizoamorim/558-bridge-page
* luizoamorim/559-assets-send-modal
  luizoamorim/integration-from-bridge-558
  luizoamorim/save-user-hook-for-ts
