### ISSUE TITLE
Github action for ping pong test in Staging Deployment

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall_3#572]
Enable GitHub action that for every commit to master, it deploys changes to staging infrastructure, launches the ping pong test, and verifies it passes.

if test passes, commit tag should be updated in deployment repo as the last valid version.

if test fails, it shouldn’t prevent from pushing to master, but at least we know there is something that needs fixing.

**Comment by Westlad** [comment]
We no longer have a staging deploy from master so closing this PR
