### ISSUE TITLE
Update deployer so that it can deploy to Goerli

### ISSUE THREAD

**Issue by Westlad** [EYBlockchain/nightfall_3#582]
Polygon runs its testnet on Goerli, so we will deploy to that testnet.  `Deployer` currently doesn't have a network stanza that would enable it to do that.  Note that both the conventional nightfall start script and the ping-pong start script, and the Github actions that deploy to Ropsten, will also need updating as part of this issue so that a Goerli deployment can be selected.

Definition of done: All nightfall deployment scripts capable of deploying to Ropsten are now able to deploy to Goerli as well, selectable via a command line argument or environment variable as appropriate.

**Comment by druiz0992** [comment]
I added this to truffle config.
https://github.com/EYBlockchain/nightfall_3/blob/5ebec5624adf04e62d032059e61d332631ecef55/nightfall-deployer/truffle-config.js#L106

Not sure we need more?

**Comment by Westlad** [comment]
That should do it.
