### ISSUE TITLE
Proposers Contract - duplicated statement

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#588]
Review L80 and 81. Proposer Set function called twice

https://github.com/EYBlockchain/nightfall_3/blob/master/nightfall-deployer/contracts/Proposers.sol#L80

**Comment by IlyasRidhuan** [comment]
This is not a duplicate statement, L80 updates the `currentProposer` entry since `currentProposer.previousAddress` must now point to `msg.sender` (the newly registered address) . L81 sets the newly registered proposer (`msg.sender`)

**Comment by druiz0992** [comment]
Ok, so can I close this then @IlyasRidhuan ?
