### ISSUE TITLE
integrate wallet websocket infrastructure in production environment

### ISSUE THREAD

**Issue by druiz0992** [EYBlockchain/nightfall_3#591]
Add the following components for each deployment environment

- [x] DynamoDB Websocket Table
- [x] API GW
- [x] Connect Lambda : register wallet ws to DynamoDB Websocket Table
- [x] Disconnect Lambda: unregister wallet ws from DynamoDB
- [x] Sync Lambda: When requested, retrieve block info from DocumentDb and send back through websocket
- [x] Stream: current publisher table. Monitor changes on documentDb and send them via websocket to wallet

**Comment by ChaitanyaKonda** [comment]
Moving this requirement to enhancement

Sync Lambda: When requested, retrieve block info from DocumentDb and send back through websocket
