### ISSUE TITLE
Error when starting wallet

### ISSUE THREAD

**Issue by vardan10** [EYBlockchain/nightfall_3#595]
After running the wallet setup as suggested by [Readme](https://github.com/EYBlockchain/nightfall_3#wallet), wallet fails to startup because it cant find following files:
[zokrates/deposit_stub/artifacts/deposit_stub-abi.json](https://github.com/EYBlockchain/nightfall_3/blob/master/wallet/src/nightfall-browser/services/deposit.js#L24)
[zokrates/deposit_stub/artifacts/deposit_stub-program](https://github.com/EYBlockchain/nightfall_3/blob/master/wallet/src/nightfall-browser/services/deposit.js#L26)

I tried to exec into the zokrates container but couldn't find any artifacts folder containing this files.

**Comment by signorecello** [comment]
I believe [this PR](https://github.com/EYBlockchain/nightfall_3/pull/583) updates the README on how to get those files

**Comment by Westlad** [comment]
Closing as resolved.
