### ISSUE TITLE
Make Proposer and Optimist sockets more aware of each other

### ISSUE THREAD

**Issue by IlyasRidhuan** [EYBlockchain/nightfall_3#665]
Proposer and optimist currently operate on a "fire-and-forget" basis when blocks are created by optimist and sent to proposer.

Any blocks sent by optimist but missed by proposer requires a lengthy restart process in order to undo changes in the optimist database. This can be improved by a better "handshake" procedure between the two.

This could involve: waiting for acknowledgements, checking block numbers, checking liveness, etc.

**Comment by druiz0992** [comment]
An example of how a proposer can fail is when a proposer submits a block and a EVM revert is returned. The proposer will not attempt to build any more blocks.

**Comment by druiz0992** [comment]
The basic idea here would be to implement a ACK from the receiver so that transmitter know message was received. If not, then it will retry for a maximum number of times.

This functionality will be used with proposer and with challenger
