### ISSUE TITLE
How to deploy and setup own erc20 on nightfall

### ISSUE THREAD

**Issue by mbcse** [EYBlockchain/nightfall_3#672]
How I can setup my own ERC20 token on nightfall that is deployed in testnet and mainet beta

**Comment by Westlad** [comment]
Hi @mbcse.  At the moment you can't.  Nightfall is actually agnostic to which tokens it interacts with; so long as they are ERC20 and you know the contract's address, you're good.  However, we restrict the tokens that can be used via the `setRestrictions` function in `Config.sol`.  This is to keep things simple while we're in beta.
Of course, you are free to deploy your own version to testnet if you want to experiment, then you can set different restrictions (check out the `default.js` config as the intial values for `setRestrictions` are read from there during deployment).

**Comment by Westlad** [comment]
Please note, I'm not implying that in the future we will allow any and all tokens. We've not decided yet.

**Comment by Westlad** [comment]
You may prefer to ask questions like this in our [discord](https://discordapp.com/channels/961162079576924202/967983182429425684) chat.

**Comment by mbaccubit** [comment]
Oh okay thanks for the reply!

**Comment by mbcse** [comment]
oh okay thanks for your reply!
