### ISSUE TITLE
findUsableCommitments does not handle the case of less than 2 commitments in DB, hence no spend can be done. Needs to handle by addingif (onlyOne) return null if (commitments.length < 2) throw new Error("not enough commitments to perform spend")

### ISSUE THREAD

**Issue by itshanh** [EYBlockchain/nightfall_3#738]

**Comment by Westlad** [comment]
This is not an issue.  If commitments are required and none are found, null is returned by the database search. This is not an error, it's intended behaviour for a function that only has a database as its concern.  The implication of not finding commitments when you expected to find them is correctly handled by the function that wanted them (e.g. `transfer` or `withdraw`. These functions do throw.
