### ISSUE TITLE
deleteCommitments in rollback handler of client not working. To test this run adversary-test.mjs. Sibling path also exists for these commitments

### ISSUE THREAD

**Issue by itshanh** [EYBlockchain/nightfall_3#739]

**Comment by LijuJoseJJ** [comment]
issue is not with deleteCommitments, issue is adversary-test.mjs test that it do not create a case yet where rollback event of client have any commits to be rolled back, so always deleteCommitments is querying with empty commitments array

**Comment by LijuJoseJJ** [comment]
with current update to adversary test and adversary code,  deleteCommitments logic of nightfall-client is working now
