### ISSUE TITLE
Implementing white lists

### ISSUE THREAD

**Issue by hnhngn** [EYBlockchain/nightfall_3#742]
Provide a means to prevent anyone but an authorised user from moving funds between Layer 1 and Layer 2.
There should be a specific group of Ethereum addresses with the power to authorise/de-authorise individuals (whitelist-managers) and these should each be able to manage a specific group of users.  Whitelist managers can be added/removed via the Nightfall Multisig contract using the administrator container.  Additionally, a preliminary set of whitelist managers can be specified at deployment.
Whitelist-managers can also be a smart contract to enable later expansion to multisigs, DAOs and automated KYC.

**Comment by Westlad** [comment]
Approaches documented. Currently blocked until decision is made in implementation.
