### ISSUE TITLE
Client database needs to react to rollback situations

### ISSUE THREAD

**Issue by Westlad** [EYBlockchain/nightfall_3#88]
If there is a rollback, both Timber and Optimist will reset their state appropriately.  However this may leave the Client commitment database inconsistent with Timber (and thence the blockchain record).  This needs addressing.

**Comment by Westlad** [comment]
I think this is mostly ok but not completely.  Before a commitment is spent, Client will check with Timber that the commitment is known to Timber, and will ignore it (not attempt to spend it) if not.  This will prevent Client trying to spend commitments that were reverted in a rollback - although it would be nice to prune these from the client database eventually.  That's actually a bit tricky because we shouldn't assume a commitment is invalid just because Timber doesn't know about it, there may be a syncing issue.  It's a future improvement I suggest.

However, once a commitment is spent, it's possible that a rollback may revert that spend.  Currently there's not a way for Client to recover from that.  This means that a token that has once again become spendable because of a rollback will remain marked as nullified.

**Comment by Westlad** [comment]
Optimist maintains a list of nullifiers that are in a layer 2 block - that is, they represent a spent commitment.  We can add this check to Client alongside the commitment 'known to Timber' check.  We then ignore the 'isNullified' flag in client because it's not a good measure of whether a commitment is considered nullified (because of a rollback) and instead check directly with Optimist.
The only issue here is that Optimist might be out of sync, in which case we may not select a commitment that we could have spent (not a big issue, this will come right with syncing), or we may attempt to spend a commitment that actually is nullified. That will ultimately fail because either a proposer will realise the commitment is spent (via their Optimist instance) and we will have spent ~ 8k Gas needlessly (not the end of the world) or, ultimately, if the proposer also doesn't notice then the L2 block they make will be challengable.

**Comment by Westlad** [comment]
If necessary, we could put a lock on spent commitments for a short time, to ensure they're not spent multiple times by rapidly firing off transactions from Client.  We'll add this if it turns out to be needed.

**Comment by IlyasRidhuan** [comment]
I believe this issue also applies to how `optimist` handles Rollbacks. In fact in the long term, solving the problem in `optimist` should also solve this issue with `client`. This is even more true if future enhancements has `client` looking to `optimist` as a THE source of truth.

Currently, a typical situation that triggers a database correction is the following:
blockProposed -> saveBlock -> checkBlock -> issueChallenge -> Rollback -> adjustLocalDatabases.

The problem is that in `adjustingLocalDatabases` there is no re-verification of the correctness of the local state - commitments could become unspendable. Compounding this, `optimist` treats everything in its database as being correct and verified - resulting in potentially invalid transactions being inadvertently included in a future block.

If we solve this problem, we can then trigger a message to `client` (maybe through a websocket/ hook) to inform it of changes to its local `commitments` store.

**Comment by Westlad** [comment]
> Compounding this, optimist treats everything in its database as being correct and verified - resulting in potentially invalid transactions being inadvertently included in a future block.
I'm not quite sure I follow this.  The transactions are validated before insertion into the database so they are known to be correct (assuming the validation is sound).  Was there a particular circumstance that you were thinking of?

**Comment by IlyasRidhuan** [comment]
I have two valid transactions: `tx_a` and `tx_b` where they are dependently linked such that `tx_b` spends a commitment from `tx_a`. They occur in two different L2 blocks both within the challenge window. 

A multi-block rollback occurs such that both `tx_a` and `tx_b` end up back in the mempool - note that `addTransactionsToMemPool`, which does this action, is merely setting the `mempool` flag to `true`.

Now in `block-assembler`  we may include `tx_b` (it may have a higher fee) before `tx_a` which would constitute an challengeable block even though we are havent done anything malicious as an `optimist`

**Comment by Westlad** [comment]
Ah, that's interesting. If tx_b spends a commitment created in tx_a then tx_b must refer to a merkle historic root (via an L2 block number) in which tx_a's commitment exists.  However, that root does not exist, because it's been rolled back.  Thus tx_b would fail the validity check with `incorrectHistoricRoot`.  If that's ok so far, we could fix it by validating the historic root before we drop tx_b back in the mempool and rejecting if it fails?

**Comment by IlyasRidhuan** [comment]
i'd need to think about it more (if `incorrectHistoricRoot` is the only extra verification required) but i would not be opposed to adding more logic to the block assembler - e.g. prioritising "safe" transactions that have commitments outside the challenge window, packaging related transactions (if we ever get to the stage of enabling parent-child transactions within the same block)
