### ISSUE TITLE
Spike: Review impact of changing web3 with ethers

### ISSUE THREAD

**Issue by daveroga** [EYBlockchain/nightfall_3#888]
We have seen Web3 has some vulnerabilities in the libraries they use because of `swarm-js` using a library with vulnerabilities that is `got: 7.1.0`.
We will investigate the impact of moving this `web3` with `ethers` library access the functionality about the contracts.

Document created for collection of different sources about migration from web3 to ethers for this spile: 
https://hackmd.io/amVLUwo0TuuD1YGvXmnSTA

## Test
Branch created for this spike to be tested `daveroga\ethers-test` which migrate the `cli` project from `web3` to `ethers` to use `nf3` with `ethers`. You can run `npm run test-e2e-tokens` and tests will be done through the new `nf3` with `ethers`.

**Comment by Westlad** [comment]
The vulnerabilities are fixed in PR #908 by overriding the version of Got used.

**Comment by pawelgrzybek** [comment]
@Westlad override is a good temporary solution until we have a fix in web3 itself. I would personally do this as an individual PR tho.

**Comment by Westlad** [comment]
@pawelgrzybek I'm fine with including it in the PR, I take your point but I consider it to be a necessary part of the upgrade so I'm not minded to split it into two PRs.
