### ISSUE TITLE
Remove public inputs hash

### ISSUE THREAD

**Issue by Westlad** [EYBlockchain/nightfall_3#89]
We currently hash public elements of a zksnark.  This is gas-efficient because the verification key length is minimised and the verification algorithm thus uses a minimum of gas.  However, the hash needs to be computed as part of the zksnark circuit and this is a major driver of constraint count and thus the time needed to compute a proof.  The problem is compounded by the use of a SHA256 hash to keep gas costs low (because in a non-optimistic solution the hash has to be recomputed on-chain for each transaction).

For NF_3, we only do an on-chain verification in the case of a challenge so we're less sensitive to Gas costs. Thus, we can remove the hashing of the public inputs and use the public input directly in the circuit. In this way we benefit from faster proof computation.

**Comment by MirandaWood** [comment]
Circuits complete in `miranda/remove-input-hash`, Solidity/nodejs changes in progress
