### ISSUE TITLE
Move from web3 to ethers. Move from truffle to hardhat

### ISSUE THREAD

**Issue by signorecello** [EYBlockchain/nightfall_3#918]

**Comment by siosw** [comment]
## Current Results
* the startup time of the nightfall testing environment is improved
* one problem with this is that hardhat does not support web sockets wich is something we current need for some of the e2e our tests to work, see [this issue](https://github.com/ethers-io/ethers.js/issues/1053)
* using HH + fixtures seems will increase test performance
* WIP see #1044

time results:
```
on ganache chain:
npm run test-e2e-protocol  3.81s user 0.86s system 10% cpu 45.499 total

on HH chain:
npm run test-e2e-protocol  3.98s user 0.77s system 10% cpu 44.498 total

on HH chain w/ parallel flag
npx hardhat test test/e2e/protocol/* --bail --no-compile --parallel  5.19s user 0.73s system 15% cpu 37.905 total

on HH chain with fixtures:
npx hardhat test test/e2e/protocol/proposer.hh.test.mjs --network localhost  1.98s user 0.32s system 20% cpu 11.157 total
```

takeaway: it is feasible to run our tests on HH / but we need to modify tests to change our testing strategy to fully take advantage of fixtures to get significant performance gains

### possible next steps
* get websocket tests to work with HH, maybe using [this package](https://www.npmjs.com/package/@sebasgoldberg/hardhat-wsprovider)
* the deployer shouldn’t exist as a docker container
* remove dependency on truffle
* derive the on chain test state from the DB state when setting up tests
