### ISSUE TITLE
Endpoint to know the status of Polygon Nightfall externally

### ISSUE THREAD

**Issue by daveroga** [EYBlockchain/nightfall_3#922]
Healthcheck for Polygon Nightfall.
- Review dashboard in the infra that has information about the different services (proposers, challengers, optimist, etc).
- Create and endpoint to be consumed externally in order to know the status of Polygon Nightfall service.
- Export dashboard nightfall status via endpoint

**Comment by druiz0992** [comment]
done in https://github.com/EYBlockchain/nightfall_3_private/pull/279
