### ISSUE TITLE
Migrate functionality from the old SDK

### ISSUE THREAD

**Issue by signorecello** [EYBlockchain/nightfall_3#945]
As part of the new proposer/challenger SDK, most functionality needs to be migrated from the old SDK into this one. Structure should be already in place

**Comment by signorecello** [comment]
duplicate of #892

**Comment by imagobea** [comment]
@signorecello closing this one as either this is a duplicate of #1025, or it refers to all the features that need "re-writing" - for which I'm creating smaller tickets based on dRuiz requirements. Thanks!
