### ISSUE TITLE
Setup folder structure and tools for the new SDK

### ISSUE THREAD

**Issue by signorecello** [EYBlockchain/nightfall_3#948]
A suggestion would be to pick up most of the standards from the user SDK and use that as a basis (regarding linting, structure, test framework, etc).

We need to have this set up before starting to migrate functionality from the old SDK

- [ ] Linting
- [ ] TS

- [ ] Folder structure

- [ ] Testing framework (mocha vs jest)

- [ ] Modularization

**Comment by imagobea** [comment]
No longer valid
