### ISSUE TITLE
Prevent proposers from unregistering if they have pending blocks that could still be challenged

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/nightfall_3#98]
This is already flagged in the code as a TODO (see pic) 
<img width="317" alt="image" src="https://user-images.githubusercontent.com/42943676/124760057-42f57300-df28-11eb-973a-12439c867dfe.png">

One simple solution to this is to make proposers wait a week before they can 'deregister' (or at least, before they can withdraw their original bond). This is what optimism does (https://research.paradigm.xyz/optimism#incentives--bonds).

**Comment by IlyasRidhuan** [comment]
My preference is to let the proposer deregister whenever but escrow the bond for the challenge period like optimism. We seem to use `pendingWithdrawals` as the holding area for "non-transactor funds wanting to be withdrawn to L1" (i.e. blockProposal fees, rewards from challenges, Bonds). This makes enforcing time-constraints on withdrawals from here difficult - without impacting non-proposers.

The alternative is trying to answer the question: "Does the this proposer have blocks in the challenge window". I don't think our current setup makes it easy to answer the question as the `proposer` info is only stored in the calldata.

Unless I've missed something, i think we might have to brainstorm a better way of handling `pendingWithdrawals`.

**Comment by IlyasRidhuan** [comment]
As a side note, i think this function is quite incomplete. It needs to behave similar to `removeProposer` but preserving the bond.

1. Do we allow the `currentProposer` to de-register? If so, we will need to rotate proposers or we will have idle time.
2. While we unset the proposer address in `proposers` we do not seem to "un-splice" the proposer from the doubly-linked list. This would mean at some point `changeCurrentProposer` will assign the next proposer to be this newly de-registered proposer.
